config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end

  root 'pages#landing'
  get 'pages/about'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :todo_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    redirect_to '/todo_lists' if user_signed_in?
  end

  def about

  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def edit
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = 'Todo List item was deleted.'
    else
      flash[:error] = 'Todo List item could not be deleted.'
    end
    redirect_to @todo_list
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: 'Todo item completed'
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @todo_lists = TodoList.all
  end


  def show
  end


  def new
    @todo_list = current_user.todo_lists.build
  end


  def edit
  end

  def create
    @todo_list = current_user.todo_lists.build(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def todo_list_params
    params.require(:todo_list).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todogarag</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
    <div class="container-fluid bg-img">
      <div class="container">
        <div class="row">
          <div class="col-md-10">
            <div class="nav">
              <%= link_to "Главная", root_path, class: 'nav-link' %>
              <%= link_to "О нас", pages_about_path, class: 'nav-link' %>
              <% if user_signed_in? %>
                <%= link_to "Выйти",  destroy_user_session_path, class: 'nav-link', method: :delete  %>
              <% end %>
            </div>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
          </div>
        </div>
      </div>
      <%= yield %>



    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>О создателе</h1>
<p>ToDo Garag - планируй</p>

app/views/pages/landing.html.erb
<% if user_signed_in? %>

<% else %>
  <div class="jumbotron">
    <h1 class="display-4">Добро пожыловать</h1>
    <p class="lead">ToDo Garag - планируй</p>
    <hr class="my-4">

    <%= link_to 'Создать аккаунт', 'users/sign_up', class: 'btn btn-danger btn-lg' %>
    <%= link_to 'Войти', 'users/sign_in', class: 'btn btn-primary btn-lg' %>

  </div>

  <% end %>

app/views/todo_items/_edit_item.html.erb
<h1>Editing Todo task</h1>

<%= render 'form', todo_item: todo_items %>

<%= link_to 'Show', @todo_item %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New Todo" %>
  <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
  <% if todo_item.completed? %>
    <div class="complete">
      <%= link_to "Mark as Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %>
    </div>
    <div class="todo_item">
      <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
    </div>
    <div class="trash">
      <%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  <% else %>
    <div class="complete">
      <%= link_to "Mark as Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %>
    </div>
    <div class="todo_item">
      <p><%= todo_item.content %></p>
    </div>
    <div class="trash">
      <%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 m-auto">
      <div class="jumbotron">
        <div class="header_todo_list d-flex justify-content-around">
          <div class="wrap-icon">
           <i class="fa fa-bandcamp" aria-hidden="true"></i>
          </div>
          <h1 class="display-4">Todo Lists</h1>
          <div class="wrap-icon">
            <i class="fa fa-bandcamp" aria-hidden="true"></i>
          </div>
        </div>
          <table class="table table-hover" >
            <thead>
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
            <% @todo_lists.each do |todo_list| %>
              <% if todo_list.user == current_user %>
                <tr>
                  <td><%= todo_list.title %></td>
                  <td><%= todo_list.description %></td>
                  <td><%= link_to 'Show', todo_list %></td>
                  <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
                  <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            <% end %>
            </tbody>
          </table>
        <br>
        <%  if user_signed_in? %>
          <%= link_to 'New Todo List', new_todo_list_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p><h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p><!-- WE DONT NEED ANYMORE!
<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p><p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>
--><div id="todo_items_wrapper">
  <%= render @todo_list.todo_items %>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
</div>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>